name: kpis-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - python-dotenv
  - pandas
  - langchain
  - langchain-openai
  - feedparser
  - flask
  - seaborn
  - matplotlib-base
  - scipy